# 개정 크롤링
### 조건 별 크롤링
- 불러오는 데이터 : 1차 크롤링을 바탕으로 확인한 데이터들
- 검색했을 때 첫번째 나오는 것들인 경우는 이전 방법대로 정상적으로 진행
- 두번째 이후 나온 것들은 나온 것들끼리 묶어서 진행
    - 포맷팅 이용해서 크롤링해보기
- 검색했는데 나오지 않는 것들은 제외
- 예상 한 300개 정도 생략될 것임 -> 나중에 추가로 찾을 수 있다면 찾아보는 것으로?
- 이후에 이를 중심으로 리뷰를 분석해보고, 협업 필터링을 중심으로 추천시스템 구현

In [1]:
import pandas as pd
import numpy as np
from selenium import webdriver
import time
from bs4 import BeautifulSoup
import requests
from selenium.webdriver.common.keys import Keys
import urllib

In [2]:
# 처리 완료되면 바꿔줘야함
df=pd.read_csv('./data/죽기전에 가봐야할 101가지 여행지.csv')
df

            여행지
0           경복궁
1        삼청동 거리
2           인사동
3           조계사
4           청와대
..          ...
994         쇠소깍
995      백조일손지묘
996  휴애리 자연생활공원
997        안덕계곡
998    제주 감귤박물관

[999 rows x 1 columns]

In [3]:
df=pd.read_csv('./data/여행지 명칭 확인_통합본.csv')
df

             여행지 일치여부 다른 칸에 존재여부
0            경복궁    O        NaN
1         삼청동 거리    O        NaN
2            인사동    O        NaN
3            조계사    O        NaN
4            청와대    O        NaN
...          ...  ...        ...
999          쇠소깍    O        NaN
1000      백조일손지묘    X          X
1001  휴애리 자연생활공원    O        NaN
1002        안덕계곡    X          X
1003    제주 감귤박물관    O        NaN

[1004 rows x 3 columns]

In [4]:
df_c=df[df['일치여부']=='O']
df_c=df_c[['여행지','일치여부']]
df_c.head()

      여행지 일치여부
0     경복궁    O
1  삼청동 거리    O
2     인사동    O
3     조계사    O
4     청와대    O

In [5]:
df_x=df[df['일치여부']=='X']
df_x

          여행지 일치여부 다른 칸에 존재여부
6         이화장    X          X
11        대학로    X          X
24        정동길    X          X
36      이슬람사원    X          X
45     최순우 옛집    X          X
...       ...  ...        ...
994    추사 거적지    X          X
995     정석항공관    X          X
997   제주 조각공원    X          X
1000   백조일손지묘    X          X
1002     안덕계곡    X          X

[356 rows x 3 columns]

In [6]:
df_xx=df_x[df_x['다른 칸에 존재여부']!='X']
df_xx

                     여행지 일치여부 다른 칸에 존재여부
51                 월드컵공원    X          2
53     대한민국 국회의사당과 헌정기념관    X          3
66             암사동 선사주거지    X          2
69                    화성    X          2
70               안양 예술공원    X          4
81          부천 활박물관과 궁도장    X          2
84                   대부도    X          2
94          국립현대미술관(과천관)    X          2
120              파주 프로방스    X          8
123                 설봉공원    X          4
124               세계도자센터    X          2
134                  청룡사    X          6
147                 융ㆍ건릉    X          2
150                  용궁사    X          6
160                  산사원    X          2
172             운악산과 현등사    X          2
175         자라섬 국제재즈페스티벌    X          2
192                 자유공원    X          3
304                  정암사    X          3
330                통일전망대    X          2
356                  탄금대    X          3
384                독립기념관    X          2
390                  공산성    X          2
395                 무령왕릉    X          2
398                충청수영성    X          2
409       천주교 대전교구 공세리성당    X          2
437            그림이 있는 정원    X          5
443             십리포 해수욕장    X          2
457            팜카밀레 허브농원    X          2
463        천주교 전주교구 전동성당    X          2
464                  한벽당    X          6
487                  대둔산    X          4
492  무주 구천동계곡 방화동 가족휴양촌,    X          2
494             마이산 도립공원    X          5
546           순천 드라마세트장     X          2
552              순천만 갈대밭    X          2
582            지리산 산수유마을    X          3
590          벌교 홍교, 대한다원    X          8
591                 봇재다원    X          8
627                  용천사    X          2
678                   계림    X          2
710                  금오산    X          2
733                 빙계계곡    X          2
736              군위 삼존석굴    X          2
792                주남저수지    X          2
797                  청곡사    X          2
805                 달아공원    X          6
816              항공우주박물관    X          3
849               창녕 석빙고    X          3
856              고성 탈박물관    X          2
863                  임진성    X          2
963                다랑쉬오름    X          2
978                  약천사    X          2
983                제주 올레    X          2
991                천제연폭포    X          3

In [9]:
df_xx.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 55 entries, 51 to 991
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   여행지         55 non-null     object
 1   일치여부        55 non-null     object
 2   다른 칸에 존재여부  55 non-null     object
dtypes: object(3)
memory usage: 1.7+ KB

In [10]:
df_x[df_x['다른 칸에 존재여부']=='X'].count()

여행지           301
일치여부          301
다른 칸에 존재여부    301
dtype: int64

In [11]:
df_c

             여행지 일치여부
0            경복궁    O
1         삼청동 거리    O
2            인사동    O
3            조계사    O
4            청와대    O
...          ...  ...
996      알뜨르 비행장    O
998      이중섭 미술관    O
999          쇠소깍    O
1001  휴애리 자연생활공원    O
1003    제주 감귤박물관    O

[613 rows x 2 columns]

In [12]:
df_xx = df_xx.reset_index(drop = True)

In [13]:
df_xx = df_xx.astype({'다른 칸에 존재여부': 'int'})

In [23]:
df_xx.dtypes

여행지           object
일치여부          object
다른 칸에 존재여부     int32
dtype: object

In [14]:
df_xx

                    여행지 일치여부  다른 칸에 존재여부
0                 월드컵공원    X           2
1     대한민국 국회의사당과 헌정기념관    X           3
2             암사동 선사주거지    X           2
3                    화성    X           2
4               안양 예술공원    X           4
5          부천 활박물관과 궁도장    X           2
6                   대부도    X           2
7          국립현대미술관(과천관)    X           2
8               파주 프로방스    X           8
9                  설봉공원    X           4
10               세계도자센터    X           2
11                  청룡사    X           6
12                 융ㆍ건릉    X           2
13                  용궁사    X           6
14                  산사원    X           2
15             운악산과 현등사    X           2
16         자라섬 국제재즈페스티벌    X           2
17                 자유공원    X           3
18                  정암사    X           3
19                통일전망대    X           2
20                  탄금대    X           3
21                독립기념관    X           2
22                  공산성    X           2
23                 무령왕릉    X           2
24                충청수영성    X           2
25       천주교 대전교구 공세리성당    X           2
26            그림이 있는 정원    X           5
27             십리포 해수욕장    X           2
28            팜카밀레 허브농원    X           2
29        천주교 전주교구 전동성당    X           2
30                  한벽당    X           6
31                  대둔산    X           4
32  무주 구천동계곡 방화동 가족휴양촌,    X           2
33             마이산 도립공원    X           5
34           순천 드라마세트장     X           2
35              순천만 갈대밭    X           2
36            지리산 산수유마을    X           3
37          벌교 홍교, 대한다원    X           8
38                 봇재다원    X           8
39                  용천사    X           2
40                   계림    X           2
41                  금오산    X           2
42                 빙계계곡    X           2
43              군위 삼존석굴    X           2
44                주남저수지    X           2
45                  청곡사    X           2
46                 달아공원    X           6
47              항공우주박물관    X           3
48               창녕 석빙고    X           3
49              고성 탈박물관    X           2
50                  임진성    X           2
51                다랑쉬오름    X           2
52                  약천사    X           2
53                제주 올레    X           2
54                천제연폭포    X           3

2번째 : #BODY_BLOCK_JQUERY_REFLOW > div.page > div > div.ui_container.main_wrap > div > div > div > div > div.content_column.ui_column.is-9-desktop.is-12-tablet.is-12-mobile > div > div.ui_columns.sections_wrapper > div > div.prw_rup.prw_search_search_results.ajax-content > div > div.main_content.ui_column.is-12 > div > div:nth-child(2) > div > div > div:nth-child(2) > div > div > div > div.ui_column.is-9-desktop.is-8-mobile.is-9-tablet.content-block-column > div

3번째 : #BODY_BLOCK_JQUERY_REFLOW > div.page > div > div.ui_container.main_wrap > div > div > div > div > div.content_column.ui_column.is-9-desktop.is-12-tablet.is-12-mobile > div > div.ui_columns.sections_wrapper > div > div.prw_rup.prw_search_search_results.ajax-content > div > div.main_content.ui_column.is-12 > div > div:nth-child(2) > div > div > div:nth-child(3) > div > div > div > div.ui_column.is-9-desktop.is-8-mobile.is-9-tablet.content-block-column > div

 driver.find_element_by_css_selector('#BODY_BLOCK_JQUERY_REFLOW > div.page > div > div.ui_container.main_wrap > div > div > div > div > div.content_column.ui_column.is-9-desktop.is-12-tablet.is-12-mobile > div > div.ui_columns.sections_wrapper > div > div.prw_rup.prw_search_search_results.ajax-content > div > div.main_content.ui_column.is-12 > div > div:nth-child(2) > div > div > div:nth-child(%d) > div > div > div > div.ui_column.is-9-desktop.is-8-mobile.is-9-tablet.content-block-column > div').click()
 
 
 #BODY_BLOCK_JQUERY_REFLOW > div.page > div > div.ui_container.main_wrap > div > div > div > div > div.content_column.ui_column.is-9-desktop.is-12-tablet.is-12-mobile > div > div.ui_columns.sections_wrapper > div > div.prw_rup.prw_search_search_results.ajax-content > div > div.main_content.ui_column.is-12 > div > div:nth-child(2) > div > div > div:nth-child(2) > div > div > div > div.ui_column.is-9-desktop.is-8-mobile.is-9-tablet.content-block-column > div

In [7]:

options=webdriver.ChromeOptions()
options.add_argument('user_agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36')
options.add_experimental_option("excludeSwitches", ["enable-logging"])


driver=webdriver.Chrome()
url='https://www.tripadvisor.co.kr/'

reviews=[]
for i in range(len(df_c)):
    driver.get(url)
    search=df_c.여행지[i]
    driver.find_element_by_css_selector('#lithium-root > main > div.dqRmR.dcDXR.dJjeH > div > div > div.weiIG.Z0.Wh.fRhqZ > form > input.fhEMT._G.B-.z._J.Cj.R0').send_keys(search)
    driver.find_element_by_css_selector('#lithium-root > main > div.dqRmR.dcDXR.dJjeH > div > div > div.weiIG.Z0.Wh.fRhqZ > form > input.fhEMT._G.B-.z._J.Cj.R0').send_keys(Keys.ENTER)
    driver.switch_to.window(driver.window_handles[-1])
    time.sleep(2)
    try: 
        driver.find_element_by_css_selector('#BODY_BLOCK_JQUERY_REFLOW > div.page > div > div.ui_container.main_wrap > div > div > div > div > div.content_column.ui_column.is-9-desktop.is-12-tablet.is-12-mobile > div > div.ui_columns.sections_wrapper > div > div.prw_rup.prw_search_search_results.ajax-content > div > div.main_content.ui_column.is-12 > div > div:nth-child(2) > div > div > div:nth-child(1) > div > div > div > div.ui_column.is-9-desktop.is-8-mobile.is-9-tablet.content-block-column > div').click()

        driver.switch_to.window(driver.window_handles[-1])
        soup=BeautifulSoup(driver.page_source,'html.parser')
        mydata=soup.find_all('span','NejBf')
        for item in mydata:
            reviews.append(search + '-->' + item.get_text().strip())
        driver.switch_to.window(driver.window_handles[-1])
        driver.close()
        driver.switch_to.window(driver.window_handles[0])
        driver.back()
        time.sleep(1)
    except:
        pass

C:\Users\alsgu\AppData\Local\Temp/ipykernel_6764/3104573750.py:14: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  driver.find_element_by_css_selector('#lithium-root > main > div.dqRmR.dcDXR.dJjeH > div > div > div.weiIG.Z0.Wh.fRhqZ > form > input.fhEMT._G.B-.z._J.Cj.R0').send_keys(search)
C:\Users\alsgu\AppData\Local\Temp/ipykernel_6764/3104573750.py:15: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  driver.find_element_by_css_selector('#lithium-root > main > div.dqRmR.dcDXR.dJjeH > div > div > div.weiIG.Z0.Wh.fRhqZ > form > input.fhEMT._G.B-.z._J.Cj.R0').send_keys(Keys.ENTER)
C:\Users\alsgu\AppData\Local\Temp/ipykernel_6764/3104573750.py:20: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  driver.find_element_by_css_selector('#BODY_BLOCK_JQUERY_REFLOW > div.page > div > div.ui_container.main_wrap > div > div > div > div > div.content_column.ui_column.is-9-desktop.is-12-tablet.is-12-mobile > div > div.ui_columns.sections_wrapper > div > div.prw_rup.prw_search_search_results.ajax-content > div > div.main_content.ui_column.is-12 > div > div:nth-child(2) > div > div > div:nth-child(1) > div > div > div > div.ui_column.is-9-desktop.is-8-mobile.is-9-tablet.content-block-column > div').click()

WebDriverException: Message: target frame detached
  (Session info: chrome=101.0.4951.67)
Stacktrace:
Backtrace:
	Ordinal0 [0x0052B8F3+2406643]
	Ordinal0 [0x004BAF31+1945393]
	Ordinal0 [0x003AC610+837136]
	Ordinal0 [0x0039D777+776055]
	Ordinal0 [0x0039C7C5+772037]
	Ordinal0 [0x0039CDC8+773576]
	Ordinal0 [0x0039CD58+773464]
	Ordinal0 [0x003A2F1A+798490]
	Ordinal0 [0x0039DF9B+778139]
	Ordinal0 [0x0039E4C5+779461]
	Ordinal0 [0x0039E2AF+778927]
	Ordinal0 [0x0039D8A6+776358]
	Ordinal0 [0x0039D810+776208]
	Ordinal0 [0x0039C7C5+772037]
	Ordinal0 [0x0039CDC8+773576]
	Ordinal0 [0x0039CD58+773464]
	Ordinal0 [0x003A2F1A+798490]
	Ordinal0 [0x0039DF9B+778139]
	Ordinal0 [0x0039E4C5+779461]
	Ordinal0 [0x0039E2AF+778927]
	Ordinal0 [0x0039D8A6+776358]
	Ordinal0 [0x0039D11C+774428]
	Ordinal0 [0x0039CFB9+774073]
	Ordinal0 [0x003ADB00+842496]
	Ordinal0 [0x00403F4B+1195851]
	Ordinal0 [0x003F4096+1130646]
	Ordinal0 [0x003CE636+976438]
	Ordinal0 [0x003CF546+980294]
	GetHandleVerifier [0x00799612+2498066]
	GetHandleVerifier [0x0078C920+2445600]
	GetHandleVerifier [0x005C4F2A+579370]
	GetHandleVerifier [0x005C3D36+574774]
	Ordinal0 [0x004C1C0B+1973259]
	Ordinal0 [0x004C6688+1992328]
	Ordinal0 [0x004C6775+1992565]
	Ordinal0 [0x004CF8D1+2029777]
	BaseThreadInitThunk [0x75C6FA29+25]
	RtlGetAppContainerNamedObjectPath [0x779A7A7E+286]
	RtlGetAppContainerNamedObjectPath [0x779A7A4E+238]

In [8]:
reviews

['경복궁-->대한민국의 역사',
 '경복궁-->대한민국의 역사가 잠들어 있는 곳. 서울을 방문했다면 꼭 방문해야 되는 곳. 경복궁은 우리의 역사다. 넓은 경복궁을 산책할 수 있는 것은 언제나 행복이다.',
 '경복궁-->국민이 공감하는 장소',
 '경복궁-->경복궁은 국민들이 자주 찾는곳으로 작성자는 주말에 자주 가족들과 방문하고 있음.특히 가족들과 방문시 옛고궁의 멋을 즐길수 있으며 쾌적한 공기와역사를 체험하고 힐링할수 있는곳임.',
 '경복궁-->산책하기 좋은 경복궁',
 '경복궁-->날씨 좋은 날 종종 산책하러 경복궁에 가는데 마음이 편온해지는 기분이라고 할까요? 특히 봄이나 가을에 산책가는 걸 추천해요!',
 '경복궁-->Good',
 '경복궁-->Goooooood 다 좋습니다 다음에 또 오고 싶네요 근처 관광지도많고 먹을거리도많네요 서울올때마다 자주이용중인데 또오고싶습니다',
 '경복궁-->가족단위로 방문하기 좋은곳',
 '경복궁-->요새 더더욱 코로나로 인해 사람 방문이 적음. 두자녀 동반시 성인 입장무료. 지금 시기에 나들이 하기 딱 좋은곳. 지하철 광화문역이나 종각역이용 편리.',
 '경복궁-->하늘이 내린 큰 복',
 "경복궁-->조선 개국 4년째인 1395년에 처음으로 세운 으뜸 궁궐이다.'하늘이 내린 큰 복' 이라는 뜻으로 경복궁이라 이름지었다.가장 아름답고 웅장한 이 경복궁은 임진왜란, 일제강점기 2번에 걸쳐 일본의 악랄하고 잔인한 파괴를 당한 악연을 갖고있다.향원정은 보수 공사로 인해 볼 수 없지만 아름다운 경회루만으로도 충분한 경복궁이다.",
 '경복궁-->굿',
 '경복궁-->한국 건축물의 아름다움을 느낄 수 있는 곳이고, 한복을 입었을 때 입장료는 무료.주변에 한복 대여점이 많으니 한번쯤 대여해서 입어보는것도 나쁘지 않을듯',
 '경복궁-->조선의 집',
 '경복궁-->조선의 성곽 안에는 박물관도 있고 경회루 등 볼것이 많다. 외국인들 및 연인들도 주변에서 한복 및 특수복장 빌려서 성을 둘러보며 데이트를 즐기기에 딱 좋다. 야간개장도 하니 잘 알아보고 올것 한국사람이라면 한번이상은 꼭와봤고 , 외국인들에게도 좋은 관광지라고 생각한다. 앞에 광화문 광장 청계천 뒤로 삼청동  이주변에 연계된 명소들도 많기 때문에 꼭 추천한다.',
 '경복궁-->대표 문화재',
 '경복궁-->대부분의 사람들이 여행을 간다면 그 나라의 유서 깊은 궁전을 찾게 된다.한국에서는 그 곳이 바로 경복궁이다.지금의 경복궁은 원래의 것보다 많이 축소되었지만 그래도 깨끗이 잘 정돈되어 있으며 위엄이 있다.',
 '경복궁-->경복궁',
 '경복궁-->몇번을 가도 감탄하게 되며 산책하기 최고인 경복궁 매번 갈때마다 정교함과 운치에 또한번 반하게 되는곳 주변에 볼거리도 많음']

In [28]:
# 포맷팅 해서 적용하는 코드 (df_xx사용)
options=webdriver.ChromeOptions()
options.add_argument('user_agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36')
options.add_experimental_option("excludeSwitches", ["enable-logging"])


driver=webdriver.Chrome()
url='https://www.tripadvisor.co.kr/'


for i in range(len(df_xx)):
    driver.get(url)
    search=df_xx.여행지[i]
    driver.find_element_by_css_selector('#lithium-root > main > div.dqRmR.dcDXR.dJjeH > div > div > div.weiIG.Z0.Wh.fRhqZ > form > input.fhEMT._G.B-.z._J.Cj.R0').send_keys(search)
    driver.find_element_by_css_selector('#lithium-root > main > div.dqRmR.dcDXR.dJjeH > div > div > div.weiIG.Z0.Wh.fRhqZ > form > input.fhEMT._G.B-.z._J.Cj.R0').send_keys(Keys.ENTER)
    
    time.sleep(2)
    
    try : 
        if df['다른 칸에 존재여부']==2:
            driver.find_element_by_css_selector('#BODY_BLOCK_JQUERY_REFLOW > div.page > div > div.ui_container.main_wrap > div > div > div > div > div.content_column.ui_column.is-9-desktop.is-12-tablet.is-12-mobile > div > div.ui_columns.sections_wrapper > div > div.prw_rup.prw_search_search_results.ajax-content > div > div.main_content.ui_column.is-12 > div > div:nth-child(2) > div > div > div:nth-child(2) > div > div > div > div.ui_column.is-9-desktop.is-8-mobile.is-9-tablet.content-block-column > div').click()
            driver.switch_to.window(driver.window_handles[-1])
            soup=BeautifulSoup(driver.page_source,'html.parser')
            mydata=soup.find_all('span','NejBf')
            for item in mydata:
                reviews.append(search + '-->' + item.get_text().strip())
            driver.switch_to.window(driver.window_handles[-1])
            driver.close()
            driver.switch_to.window(driver.window_handles[0])
            driver.back()
            time.sleep(1)
        elif df['다른 칸에 존재여부']==3:
            driver.find_element_by_css_selector('#BODY_BLOCK_JQUERY_REFLOW > div.page > div > div.ui_container.main_wrap > div > div > div > div > div.content_column.ui_column.is-9-desktop.is-12-tablet.is-12-mobile > div > div.ui_columns.sections_wrapper > div > div.prw_rup.prw_search_search_results.ajax-content > div > div.main_content.ui_column.is-12 > div > div:nth-child(2) > div > div > div:nth-child(3) > div > div > div > div.ui_column.is-9-desktop.is-8-mobile.is-9-tablet.content-block-column > div').click()
            driver.switch_to.window(driver.window_handles[-1])
            soup=BeautifulSoup(driver.page_source,'html.parser')
            mydata=soup.find_all('span','NejBf')
            for item in mydata:
                reviews.append(search + '-->' + item.get_text().strip())
            driver.switch_to.window(driver.window_handles[-1])
            driver.close()
            driver.switch_to.window(driver.window_handles[0])
            driver.back()
            time.sleep(1)
        elif df['다른 칸에 존재여부']==4:
            driver.find_element_by_css_selector('#BODY_BLOCK_JQUERY_REFLOW > div.page > div > div.ui_container.main_wrap > div > div > div > div > div.content_column.ui_column.is-9-desktop.is-12-tablet.is-12-mobile > div > div.ui_columns.sections_wrapper > div > div.prw_rup.prw_search_search_results.ajax-content > div > div.main_content.ui_column.is-12 > div > div:nth-child(2) > div > div > div:nth-child(4) > div > div > div > div.ui_column.is-9-desktop.is-8-mobile.is-9-tablet.content-block-column > div').click()
            driver.switch_to.window(driver.window_handles[-1])
            soup=BeautifulSoup(driver.page_source,'html.parser')
            mydata=soup.find_all('span','NejBf')
            for item in mydata:
                reviews.append(search + '-->' + item.get_text().strip())
            driver.switch_to.window(driver.window_handles[-1])
            driver.close()
            driver.switch_to.window(driver.window_handles[0])
            driver.back()
            time.sleep(1)
        elif df['다른 칸에 존재여부']==5:
            driver.find_element_by_css_selector('#BODY_BLOCK_JQUERY_REFLOW > div.page > div > div.ui_container.main_wrap > div > div > div > div > div.content_column.ui_column.is-9-desktop.is-12-tablet.is-12-mobile > div > div.ui_columns.sections_wrapper > div > div.prw_rup.prw_search_search_results.ajax-content > div > div.main_content.ui_column.is-12 > div > div:nth-child(2) > div > div > div:nth-child(5) > div > div > div > div.ui_column.is-9-desktop.is-8-mobile.is-9-tablet.content-block-column > div').click()
            driver.switch_to.window(driver.window_handles[-1])
            soup=BeautifulSoup(driver.page_source,'html.parser')
            mydata=soup.find_all('span','NejBf')
            for item in mydata:
                reviews.append(search + '-->' + item.get_text().strip())
            driver.switch_to.window(driver.window_handles[-1])
            driver.close()
            driver.switch_to.window(driver.window_handles[0])
            driver.back()
            time.sleep(1)
        elif df['다른칸에 존재여부']==6:
            driver.find_element_by_css_selector('#BODY_BLOCK_JQUERY_REFLOW > div.page > div > div.ui_container.main_wrap > div > div > div > div > div.content_column.ui_column.is-9-desktop.is-12-tablet.is-12-mobile > div > div.ui_columns.sections_wrapper > div > div.prw_rup.prw_search_search_results.ajax-content > div > div.main_content.ui_column.is-12 > div > div:nth-child(2) > div > div > div:nth-child(6) > div > div > div > div.ui_column.is-9-desktop.is-8-mobile.is-9-tablet.content-block-column > div').click()
            driver.switch_to.window(driver.window_handles[-1])
            soup=BeautifulSoup(driver.page_source,'html.parser')
            mydata=soup.find_all('span','NejBf')
            for item in mydata:
                reviews.append(search + '-->' + item.get_text().strip())
            driver.switch_to.window(driver.window_handles[-1])
            driver.close()
            driver.switch_to.window(driver.window_handles[0])
            driver.back()
            time.sleep(1)
        elif df['다른 칸에 존재여부']==7:
            driver.find_element_by_css_selector('#BODY_BLOCK_JQUERY_REFLOW > div.page > div > div.ui_container.main_wrap > div > div > div > div > div.content_column.ui_column.is-9-desktop.is-12-tablet.is-12-mobile > div > div.ui_columns.sections_wrapper > div > div.prw_rup.prw_search_search_results.ajax-content > div > div.main_content.ui_column.is-12 > div > div:nth-child(2) > div > div > div:nth-child(7) > div > div > div > div.ui_column.is-9-desktop.is-8-mobile.is-9-tablet.content-block-column > div').click()
            driver.switch_to.window(driver.window_handles[-1])
            soup=BeautifulSoup(driver.page_source,'html.parser')
            mydata=soup.find_all('span','NejBf')
            for item in mydata:
                reviews.append(search + '-->' + item.get_text().strip())
            driver.switch_to.window(driver.window_handles[-1])
            driver.close()
            driver.switch_to.window(driver.window_handles[0])
            driver.back()
            time.sleep(1)
        elif df['다른 칸에 존재여부']==8:
            driver.find_element_by_css_selector('#BODY_BLOCK_JQUERY_REFLOW > div.page > div > div.ui_container.main_wrap > div > div > div > div > div.content_column.ui_column.is-9-desktop.is-12-tablet.is-12-mobile > div > div.ui_columns.sections_wrapper > div > div.prw_rup.prw_search_search_results.ajax-content > div > div.main_content.ui_column.is-12 > div > div:nth-child(2) > div > div > div:nth-child(8) > div > div > div > div.ui_column.is-9-desktop.is-8-mobile.is-9-tablet.content-block-column > div').click()
            driver.switch_to.window(driver.window_handles[-1])
            soup=BeautifulSoup(driver.page_source,'html.parser')
            mydata=soup.find_all('span','NejBf')
            for item in mydata:
                reviews.append(search + '-->' + item.get_text().strip())
            driver.switch_to.window(driver.window_handles[-1])
            driver.close()
            driver.switch_to.window(driver.window_handles[0])
            driver.back()
            time.sleep(1)
        elif df['다른 칸에 존재여부']==9:
            driver.find_element_by_css_selector('#BODY_BLOCK_JQUERY_REFLOW > div.page > div > div.ui_container.main_wrap > div > div > div > div > div.content_column.ui_column.is-9-desktop.is-12-tablet.is-12-mobile > div > div.ui_columns.sections_wrapper > div > div.prw_rup.prw_search_search_results.ajax-content > div > div.main_content.ui_column.is-12 > div > div:nth-child(2) > div > div > div:nth-child(9) > div > div > div > div.ui_column.is-9-desktop.is-8-mobile.is-9-tablet.content-block-column > div').click()
            driver.switch_to.window(driver.window_handles[-1])
            soup=BeautifulSoup(driver.page_source,'html.parser')
            mydata=soup.find_all('span','NejBf')
            for item in mydata:
                reviews.append(search + '-->' + item.get_text().strip())
            driver.switch_to.window(driver.window_handles[-1])
            driver.close()
            driver.switch_to.window(driver.window_handles[0])
            driver.back()
            time.sleep(1)
        elif df['다른 칸에 존재여부']==10:
            driver.find_element_by_css_selector('#BODY_BLOCK_JQUERY_REFLOW > div.page > div > div.ui_container.main_wrap > div > div > div > div > div.content_column.ui_column.is-9-desktop.is-12-tablet.is-12-mobile > div > div.ui_columns.sections_wrapper > div > div.prw_rup.prw_search_search_results.ajax-content > div > div.main_content.ui_column.is-12 > div > div:nth-child(2) > div > div > div:nth-child(10) > div > div > div > div.ui_column.is-9-desktop.is-8-mobile.is-9-tablet.content-block-column > div').click()
            driver.switch_to.window(driver.window_handles[-1])
            soup=BeautifulSoup(driver.page_source,'html.parser')
            mydata=soup.find_all('span','NejBf')
            for item in mydata:
                reviews.append(search + '-->' + item.get_text().strip())
            driver.switch_to.window(driver.window_handles[-1])
            driver.close()
            driver.switch_to.window(driver.window_handles[0])
            driver.back()
            time.sleep(1)
        else:
            pass
    except:
        pass

C:\Users\alsgu\AppData\Local\Temp/ipykernel_20220/3573077333.py:14: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  driver.find_element_by_css_selector('#lithium-root > main > div.dqRmR.dcDXR.dJjeH > div > div > div.weiIG.Z0.Wh.fRhqZ > form > input.fhEMT._G.B-.z._J.Cj.R0').send_keys(search)
C:\Users\alsgu\AppData\Local\Temp/ipykernel_20220/3573077333.py:15: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  driver.find_element_by_css_selector('#lithium-root > main > div.dqRmR.dcDXR.dJjeH > div > div > div.weiIG.Z0.Wh.fRhqZ > form > input.fhEMT._G.B-.z._J.Cj.R0').send_keys(Keys.ENTER)

NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=101.0.4951.54)
Stacktrace:
Backtrace:
	Ordinal0 [0x007E7413+2389011]
	Ordinal0 [0x00779F61+1941345]
	Ordinal0 [0x0066C658+837208]
	Ordinal0 [0x00654480+738432]
	Ordinal0 [0x006B6999+1141145]
	Ordinal0 [0x006C3AA2+1194658]
	Ordinal0 [0x006B3F66+1130342]
	Ordinal0 [0x0068E546+976198]
	Ordinal0 [0x0068F456+980054]
	GetHandleVerifier [0x00999632+1727522]
	GetHandleVerifier [0x00A4BA4D+2457661]
	GetHandleVerifier [0x0087EB81+569713]
	GetHandleVerifier [0x0087DD76+566118]
	Ordinal0 [0x00780B2B+1968939]
	Ordinal0 [0x00785988+1989000]
	Ordinal0 [0x00785A75+1989237]
	Ordinal0 [0x0078ECB1+2026673]
	BaseThreadInitThunk [0x75FBFA29+25]
	RtlGetAppContainerNamedObjectPath [0x77187A7E+286]
	RtlGetAppContainerNamedObjectPath [0x77187A4E+238]

In [23]:
reviews

['경복궁-->대한민국의 역사',
 '경복궁-->대한민국의 역사가 잠들어 있는 곳. 서울을 방문했다면 꼭 방문해야 되는 곳. 경복궁은 우리의 역사다. 넓은 경복궁을 산책할 수 있는 것은 언제나 행복이다.',
 '경복궁-->국민이 공감하는 장소',
 '경복궁-->경복궁은 국민들이 자주 찾는곳으로 작성자는 주말에 자주 가족들과 방문하고 있음.특히 가족들과 방문시 옛고궁의 멋을 즐길수 있으며 쾌적한 공기와역사를 체험하고 힐링할수 있는곳임.',
 '경복궁-->산책하기 좋은 경복궁',
 '경복궁-->날씨 좋은 날 종종 산책하러 경복궁에 가는데 마음이 편온해지는 기분이라고 할까요? 특히 봄이나 가을에 산책가는 걸 추천해요!',
 '경복궁-->Good',
 '경복궁-->Goooooood 다 좋습니다 다음에 또 오고 싶네요 근처 관광지도많고 먹을거리도많네요 서울올때마다 자주이용중인데 또오고싶습니다',
 '경복궁-->가족단위로 방문하기 좋은곳',
 '경복궁-->요새 더더욱 코로나로 인해 사람 방문이 적음. 두자녀 동반시 성인 입장무료. 지금 시기에 나들이 하기 딱 좋은곳. 지하철 광화문역이나 종각역이용 편리.',
 '경복궁-->하늘이 내린 큰 복',
 "경복궁-->조선 개국 4년째인 1395년에 처음으로 세운 으뜸 궁궐이다.'하늘이 내린 큰 복' 이라는 뜻으로 경복궁이라 이름지었다.가장 아름답고 웅장한 이 경복궁은 임진왜란, 일제강점기 2번에 걸쳐 일본의 악랄하고 잔인한 파괴를 당한 악연을 갖고있다.향원정은 보수 공사로 인해 볼 수 없지만 아름다운 경회루만으로도 충분한 경복궁이다.",
 '경복궁-->굿',
 '경복궁-->한국 건축물의 아름다움을 느낄 수 있는 곳이고, 한복을 입었을 때 입장료는 무료.주변에 한복 대여점이 많으니 한번쯤 대여해서 입어보는것도 나쁘지 않을듯',
 '경복궁-->조선의 집',
 '경복궁-->조선의 성곽 안에는 박물관도 있고 경회루 등 볼것이 많다. 외국인들 및 연인들도 주변에서 한복 및 특수복장 빌려서 성을 둘러보며 데이트를 즐기기에 딱 좋다. 야간개장도 하니 잘 알아보고 올것 한국사람이라면 한번이상은 꼭와봤고 , 외국인들에게도 좋은 관광지라고 생각한다. 앞에 광화문 광장 청계천 뒤로 삼청동  이주변에 연계된 명소들도 많기 때문에 꼭 추천한다.',
 '경복궁-->대표 문화재',
 '경복궁-->대부분의 사람들이 여행을 간다면 그 나라의 유서 깊은 궁전을 찾게 된다.한국에서는 그 곳이 바로 경복궁이다.지금의 경복궁은 원래의 것보다 많이 축소되었지만 그래도 깨끗이 잘 정돈되어 있으며 위엄이 있다.',
 '경복궁-->경복궁',
 '경복궁-->몇번을 가도 감탄하게 되며 산책하기 최고인 경복궁 매번 갈때마다 정교함과 운치에 또한번 반하게 되는곳 주변에 볼거리도 많음',
 '삼청동 거리-->기대 이상 만족',
 '삼청동 거리-->저번달에 아주 오랜만에 다시 방문. 10년만에 재방문인데 그사이에 카페나 작은 상점 옷가게가 눈에 많이 띄었다. 서울내에 한옥건물 제발 보존 해주세요',
 '삼청동 거리-->삼청동길',
 '삼청동 거리-->삼청동길 한옥건물들을 볼수있는 거리중 한곳다만 예전에 비해 상권이 많이 없어졌어요..그래도 걸으면서 구경하기에는 좋아요.',
 '삼청동 거리-->전통과 현대의 건축양식의 조합이 주는 이색적인 도시 풍경',
 '삼청동 거리-->이 곳에서는 기와나 목재 등을 이용해 한국의 전통적인 느낌을 살린 현대식 건물이 많아서 이색적인 도시 풍경을 감상할 수 있다. 걷기만 해도 재미있다.',
 '삼청동 거리-->옛 명성은 어디로...',
 "삼청동 거리-->삼청동 팥죽 맛집 '서울에서 두번째로 맛있는 집'을 찾아 가면서 삼청동 메인거리를 걸으면서 곳곳에 임대 표시가 되어 있는 빈 가게들이 너무 많이 생긴 것을 보고 놀랐다. 이곳도 젠트리피케이션 때문에 자영업자들이 어려움을 겪고 있는 것 같은데 우리나라 대표적인 관광지인 궁 인근에 있어 우리나라 전통 공예품을 판매하는 상가들이 번성하면 좋을텐데... 아쉬움이 너무 컸다.",
 '삼청동 거리-->옛날에 비해 많이 변한..',
 '삼청동 거리-->예전엔 갈만한 식당과 카페를 줄줄이 알았는데 요즘은 정보가 없다. 그래도 갈때마다 옛 추억때문인지 정겹고 좋았다. 사람이 많이 없어서 여유롭게 가기 좋은 곳.',
 '삼청동 거리-->퇴근 후 데이트코스로 좋은 길',
 '삼청동 거리-->퇴근 후 데이트코스로 좋은 길입니다. 비교적 중심부에 위치해 있으며, 저녁에 데이트 목적으로 방문하는 분들이 많습니다. 정독도서관부터 시작해 식사 후 걷기에도 괜찮습니다.',
 '삼청동 거리-->봄 가을 방문 강추',
 '삼청동 거리-->삼청동길 방문한지 얼마 되지않았어요. 길은 좁고 다니기 불편하지만 한옥들이 몰려있고 한옥카페를 즐길수있어 좋았습니다. 더군다나 루프탑의 카페가 많아 좋았어요. 여유를 제대로 느끼실수있습니다. 그리고 수제비집 유명해요 꼭 방문해서 드셔보시길.. 짱맛',
 '삼청동 거리-->삼청동길',
 '삼청동 거리-->외국인이 많이 찾아오는 삼청동길, 주말에는 국내 여행객들까지 있어 걷기 힘들때도 있다. 인기있는 골목길 말고 조용하게 산책할 수 있는 코스도 있으니 잘 찾아보면 좋다.',
 '삼청동 거리-->한국적인 분위기가 아름다운곳',
 '삼청동 거리-->봄되면 꼭 가는 삼청동. 곳곳에 예쁜 상점들도 있고 맛있는 한식집이 많다. 사진찍기도 좋고 그냥 산책하는 것만으로도 기분 좋은 곳!',
 '삼청동 거리-->데이트 장소로 추천',
 '삼청동 거리-->데이트 장소로 추천받는 곳들 중 하나로 다양한 볼거리와 음식들이 있는 곳입니다 여기 떡볶이 집이 아주 유명하여 줄을 섭니다']

In [ ]:
titles=[]
contents=[]
for i in range(0,len(reviews),2):
    titles.append(reviews[i])
for j in range(1,len(reviews),2):
    contents.append(reviews[j])

In [ ]:
data=pd.DataFrame({'리뷰제목':titles,'내용':contents})
data

In [ ]:
data.to_csv('여행지 리뷰 1차.csv',encoding='utf-8-sig',index=False)

In [ ]:
data['관광지']=data.리뷰제목.str.split('-->').str[0]
data['리뷰제목']=data.리뷰제목.str.split('-->').str[1]
data['내용']=data.내용.str.split('-->').str[1]

In [ ]:
data=data[['관광지','리뷰제목','내용']]
data

In [ ]:
data.to_csv('여행지 리뷰 2차.csv',encoding='utf-8-sig',index=False)

- 별도 실험용 코드

In [7]:
options=webdriver.ChromeOptions()
options.add_argument('user_agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36')
options.add_experimental_option("excludeSwitches", ["enable-logging"])

basepath='C:/Users/이신행/OneDrive/바탕 화면/chromedriver_win32(1)/'
driver=webdriver.Chrome()
url='https://www.tripadvisor.co.kr/Tourism-g294196-South_Korea-Vacations.html'

driver.get(url)
search=df.여행지[0]
driver.find_element_by_css_selector('#lithium-root > header > div > nav > div > div.fUFMI > div > div.weiIG.Z0.Wh.bZZEX > form > input.fhEMT._G.B-.z._J.Cj.R0').send_keys(search)
driver.find_element_by_css_selector('#lithium-root > header > div > nav > div > div.fUFMI > div > div.weiIG.Z0.Wh.bZZEX > form > input.fhEMT._G.B-.z._J.Cj.R0').send_keys(Keys.ENTER)
driver.switch_to.window(driver.window_handles[-1])
time.sleep(2)

soup=BeautifulSoup(driver.page_source,'html.parser')
mydata=soup.find_all('div','location-meta-block')
mydata[1].get_text().strip()

AttributeError: ResultSet object has no attribute 'get_text'. You're probably treating a list of items like a single item. Did you call find_all() when you meant to call find()?

In [8]:
mydata[1].get_text().strip()

'경복궁21건의 리뷰종로구 청진동 243, 서울, 대한민국종로구 청진동 243, 서울'