In [5]:
import pandas as pd
import numpy as np
from selenium import webdriver
import time
from bs4 import BeautifulSoup
import requests
from selenium.webdriver.common.keys import Keys

In [2]:
df=pd.read_csv('죽기전에 가봐야할 101가지 여행지.csv')
df

            여행지
0           경복궁
1        삼청동 거리
2           인사동
3           조계사
4           청와대
..          ...
994         쇠소깍
995      백조일손지묘
996  휴애리 자연생활공원
997        안덕계곡
998    제주 감귤박물관

[999 rows x 1 columns]

In [3]:
df[0:5]

      여행지
0     경복궁
1  삼청동 거리
2     인사동
3     조계사
4     청와대

In [45]:
df.여행지[0]

'경복궁'

In [52]:
options=webdriver.ChromeOptions()
options.add_argument('user_agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36')
options.add_experimental_option("excludeSwitches", ["enable-logging"])

basepath='C:/Users/이신행/OneDrive/바탕 화면/chromedriver_win32(1)/'
driver=webdriver.Chrome()
url='https://www.tripadvisor.co.kr/'
driver.get(url)

search=df.여행지[0]
driver.find_element_by_css_selector('#lithium-root > main > div.dqRmR.dcDXR.dJjeH > div > div > div.weiIG.Z0.Wh.fRhqZ > form > input.fhEMT._G.B-.z._J.Cj.R0').send_keys(search)
driver.find_element_by_css_selector('#lithium-root > main > div.dqRmR.dcDXR.dJjeH > div > div > div.weiIG.Z0.Wh.fRhqZ > form > input.fhEMT._G.B-.z._J.Cj.R0').send_keys(Keys.ENTER)
driver.switch_to.window(driver.window_handles[-1])
time.sleep(1)

driver.find_element_by_css_selector('#BODY_BLOCK_JQUERY_REFLOW > div.page > div > div.ui_container.main_wrap > div > div > div > div > div.content_column.ui_column.is-9-desktop.is-12-tablet.is-12-mobile > div > div.ui_columns.sections_wrapper > div > div.prw_rup.prw_search_search_results.ajax-content > div > div.main_content.ui_column.is-12 > div > div:nth-child(2) > div > div > div:nth-child(1) > div > div > div > div.ui_column.is-9-desktop.is-8-mobile.is-9-tablet.content-block-column').click()
driver.switch_to.window(driver.window_handles[-1])
soup=BeautifulSoup(driver.page_source,'html.parser')
mydata=soup.find_all('span','NejBf')
review=[]
for item in mydata:
    review.append(item.get_text().strip())

In [58]:
review

['대한민국의 역사',
 '대한민국의 역사가 잠들어 있는 곳. 서울을 방문했다면 꼭 방문해야 되는 곳. 경복궁은 우리의 역사다. 넓은 경복궁을 산책할 수 있는 것은 언제나 행복이다.',
 '국민이 공감하는 장소',
 '경복궁은 국민들이 자주 찾는곳으로 작성자는 주말에 자주 가족들과 방문하고 있음.특히 가족들과 방문시 옛고궁의 멋을 즐길수 있으며 쾌적한 공기와역사를 체험하고 힐링할수 있는곳임.',
 '산책하기 좋은 경복궁',
 '날씨 좋은 날 종종 산책하러 경복궁에 가는데 마음이 편온해지는 기분이라고 할까요? 특히 봄이나 가을에 산책가는 걸 추천해요!',
 'Good',
 'Goooooood 다 좋습니다 다음에 또 오고 싶네요 근처 관광지도많고 먹을거리도많네요 서울올때마다 자주이용중인데 또오고싶습니다',
 '가족단위로 방문하기 좋은곳',
 '요새 더더욱 코로나로 인해 사람 방문이 적음. 두자녀 동반시 성인 입장무료. 지금 시기에 나들이 하기 딱 좋은곳. 지하철 광화문역이나 종각역이용 편리.',
 '하늘이 내린 큰 복',
 "조선 개국 4년째인 1395년에 처음으로 세운 으뜸 궁궐이다.'하늘이 내린 큰 복' 이라는 뜻으로 경복궁이라 이름지었다.가장 아름답고 웅장한 이 경복궁은 임진왜란, 일제강점기 2번에 걸쳐 일본의 악랄하고 잔인한 파괴를 당한 악연을 갖고있다.향원정은 보수 공사로 인해 볼 수 없지만 아름다운 경회루만으로도 충분한 경복궁이다.",
 '굿',
 '한국 건축물의 아름다움을 느낄 수 있는 곳이고, 한복을 입었을 때 입장료는 무료.주변에 한복 대여점이 많으니 한번쯤 대여해서 입어보는것도 나쁘지 않을듯',
 '조선의 집',
 '조선의 성곽 안에는 박물관도 있고 경회루 등 볼것이 많다. 외국인들 및 연인들도 주변에서 한복 및 특수복장 빌려서 성을 둘러보며 데이트를 즐기기에 딱 좋다. 야간개장도 하니 잘 알아보고 올것 한국사람이라면 한번이상은 꼭와봤고 , 외국인들에게도 좋은 관광지라고 생각한다. 앞에 광화문 광장 청계천 뒤로 삼청동  이주변에 연계된 명소들도 많기 때문에 꼭 추천한다.',
 '대표 문화재',
 '대부분의 사람들이 여행을 간다면 그 나라의 유서 깊은 궁전을 찾게 된다.한국에서는 그 곳이 바로 경복궁이다.지금의 경복궁은 원래의 것보다 많이 축소되었지만 그래도 깨끗이 잘 정돈되어 있으며 위엄이 있다.',
 '경복궁',
 '몇번을 가도 감탄하게 되며 산책하기 최고인 경복궁 매번 갈때마다 정교함과 운치에 또한번 반하게 되는곳 주변에 볼거리도 많음']

In [63]:
titles=[]
contents=[]
for i in range(0,len(review),2):
    titles.append(review[i])
for j in range(1,len(review),2):
    contents.append(review[j])

In [64]:
titles

['대한민국의 역사',
 '국민이 공감하는 장소',
 '산책하기 좋은 경복궁',
 'Good',
 '가족단위로 방문하기 좋은곳',
 '하늘이 내린 큰 복',
 '굿',
 '조선의 집',
 '대표 문화재',
 '경복궁']

In [65]:
len(titles)

10

In [66]:
len(contents)

10

In [68]:
data=pd.DataFrame({'리뷰제목':titles,'내용':contents})
data

             리뷰제목                                                 내용
0        대한민국의 역사  대한민국의 역사가 잠들어 있는 곳. 서울을 방문했다면 꼭 방문해야 되는 곳. 경복궁...
1     국민이 공감하는 장소  경복궁은 국민들이 자주 찾는곳으로 작성자는 주말에 자주 가족들과 방문하고 있음.특히...
2     산책하기 좋은 경복궁  날씨 좋은 날 종종 산책하러 경복궁에 가는데 마음이 편온해지는 기분이라고 할까요? ...
3            Good  Goooooood 다 좋습니다 다음에 또 오고 싶네요 근처 관광지도많고 먹을거리도많...
4  가족단위로 방문하기 좋은곳  요새 더더욱 코로나로 인해 사람 방문이 적음. 두자녀 동반시 성인 입장무료. 지금 ...
5      하늘이 내린 큰 복  조선 개국 4년째인 1395년에 처음으로 세운 으뜸 궁궐이다.'하늘이 내린 큰 복'...
6               굿  한국 건축물의 아름다움을 느낄 수 있는 곳이고, 한복을 입었을 때 입장료는 무료.주...
7           조선의 집  조선의 성곽 안에는 박물관도 있고 경회루 등 볼것이 많다. 외국인들 및 연인들도 주...
8          대표 문화재  대부분의 사람들이 여행을 간다면 그 나라의 유서 깊은 궁전을 찾게 된다.한국에서는 ...
9             경복궁  몇번을 가도 감탄하게 되며 산책하기 최고인 경복궁 매번 갈때마다 정교함과 운치에 또...

In [16]:
options=webdriver.ChromeOptions()
options.add_argument('user_agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36')
options.add_experimental_option("excludeSwitches", ["enable-logging"])

basepath='C:/Users/이신행/OneDrive/바탕 화면/chromedriver_win32(1)/'
driver=webdriver.Chrome()
url='https://www.tripadvisor.co.kr/'
driver.get(url)

reviews=[]
for i in range(len(df)):
    search=df.여행지[i]
    driver.find_element_by_css_selector('#lithium-root > main > div.dqRmR.dcDXR.dJjeH > div > div > div.weiIG.Z0.Wh.fRhqZ > form > input.fhEMT._G.B-.z._J.Cj.R0').send_keys(search)
    driver.find_element_by_css_selector('#lithium-root > main > div.dqRmR.dcDXR.dJjeH > div > div > div.weiIG.Z0.Wh.fRhqZ > form > input.fhEMT._G.B-.z._J.Cj.R0').send_keys(Keys.ENTER)
    driver.find_element_by_css_selector('#BODY_BLOCK_JQUERY_REFLOW > div.page > div > div.ui_container.main_wrap > div > div > div > div > div.content_column.ui_column.is-9-desktop.is-12-tablet.is-12-mobile > div > div.ui_columns.sections_wrapper > div > div.prw_rup.prw_search_search_results.ajax-content > div > div.main_content.ui_column.is-12 > div > div:nth-child(2) > div > div > div:nth-child(1) > div > div > div > div.ui_column.is-9-desktop.is-8-mobile.is-9-tablet.content-block-column').click()

NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"#typeahead_results > a.bPaPP.w.z._S._F.Wc.Wh.Q.B-._G.bpubK"}
  (Session info: chrome=100.0.4896.127)