In [2]:
import pandas as pd

In [5]:
df = pd.read_excel('./data/관광지,주소.xlsx')
df

            여행지                 주소     행정구역   시군구                    분류
0           경복궁  서울특별시 종로구 사직로 161      서울시   종로구       역사적인 장소 • 역사박물관
1          삼청동길    107 종로구 삼청동, 서울      서울시   종로구           즐길거리 & 랜드마크
2          인사동길        종로구 인사동, 서울      서울시   종로구   인근 지역 • 즐길거리 & 랜드마크
3           조계사   종로구 견지동 45번지, 서울      서울시   종로구    종교적인 장소 • 기념비 및 동상
4           청와대     종로구 청와대로 1, 서울      서울시   종로구               공공기관 건물
..          ...                ...      ...   ...                   ...
605     알뜨르 비행장    제주 서귀포시 대정읍 상모리  제주특별자치시  서귀포시  역사적인 장소 • 군사 기지 및 시설
606     이중섭 미술관  제주 서귀포시 이중섭로 27-3  제주특별자치시  서귀포시                 아트뮤지엄
607         쇠소깍      쇠소깍로 140, 서귀포  제주특별자치시  서귀포시                    물길
608  휴애리 자연생활공원  남원읍 신례동로 256, 서귀포  제주특별자치시  서귀포시                    공원
609    제주 감귤박물관     효돈순환로 441, 서귀포  제주특별자치시  서귀포시                전문 박물관

[610 rows x 5 columns]

In [9]:
df_a = df[['분류','여행지']]

In [ ]:
a = []
for i in range(len)

In [11]:
df['분류'].unique()

array(['역사적인 장소 • 역사박물관', '즐길거리 & 랜드마크', '인근 지역 • 즐길거리 & 랜드마크',
       '종교적인 장소 • 기념비 및 동상', '공공기관 건물', '역사적인 장소 • 즐길거리 & 랜드마크',
       '전문 박물관 • 아트뮤지엄', '공원', '역사적인 장소 • 건축물', '산',
       '역사적인 장소 • 즐길거리 & 랜드마크 • 종교적인 장소', '역사박물관',
       '즐길거리 & 랜드마크 • 유서 깊은 산책로', '역사적인 장소 • 건축물 • 가든',
       '특산물 & 기념품 가게 • 벼룩시장 & 재래시장', '종교적인 장소 • 교회 & 성당',
       '물길 • 유서 깊은 산책로', '역사적인 장소 • 즐길거리 & 랜드마크 • 건축물', '벼룩시장 & 재래시장',
       '전문 박물관', '역사적인 장소', '즐길거리 & 랜드마크 • 전망대 • 전망대 & 타워', '아트뮤지엄',
       '군사 박물관', '국립공원', '인근 지역', '공원 • 놀이터', '특산물 & 기념품 가게', '종교적인 장소',
       '역사적인 장소 • 고대 유적 • 전망대 & 타워', '기타 야외 활동', '교육적인 장소 • 역사박물관', '묘지',
       '건축물', '즐길거리 & 랜드마크 • 종교적인 장소', '놀이공원 & 테마파크',
       '역사적인 장소 • 경관이 좋은 산책로', '스포츠 컴플렉스 • 공원', '즐길거리 & 랜드마크 • 건축물',
       '자연 & 야생동물 서식지', '과학박물관 • 어린이 박물관', '역사적인 장소 • 성', '목장', '물길 • 공원',
       '동물원 • 공원 • 가든', '과학박물관 • 관측소 & 천체투영관', '가든', '가든 • 아트뮤지엄',
       '역사적인 장소 • 놀이공원 & 테마파크',
       '이제는 인기가 시들해졌지만, 그래도 파주에 간다면 한 번은 가보게  되는 곳입니다. 분위기 좋은 카페들이 밀집해 있고, 예쁜 건물들이 많아서 포토 존도 많읍니다. 언제나 사람들로 붐비는 것이 단점입니다.',
       '전망대 & 타워', '워터파크', '인근 지역 • 경관이 좋은 산책로',
       '유서 깊은 산책로 • 절경 드라이브 코스 • 경관이 좋은 산책로',
       '역사적인 장소 • 종교적인 장소 • 경관이 좋은 산책로', '강연 & 워크숍 • 농장',
       '성 • 군사 기지 및 시설 • 경관이 좋은 산책로', '교육적인 장소', '아트갤러리', '섬',
       '고대 유적 • 즐길거리 & 랜드마크', '역사적인 장소 • 공원', '하이킹 트레일', '산림 • 가든', '산림',
       '고대 유적', '물길 • 자연 & 야생동물 서식지 • 공원', '자연 & 야생동물 서식지 • 산림', '계곡',
       '물길 • 즐길거리 & 랜드마크', '가든 • 경관이 좋은 산책로', '즐길거리 & 랜드마크 • 가든', '해변',
       '역사적인 장소 • 전쟁터 유적지',
       '역사적인 장소 • 즐길거리 & 랜드마크 • 전쟁터 유적지 • 군사 기지 및 시설 • 경관이 좋은 산책로',
       '역사적인 장소 • 건축물 • 교회 & 성당', '페리 • 댐', '전문 박물관 • 시어터', '공원 • 가든',
       '문화 행사', '과학박물관', '랜드마크, 체험공간', '동굴', '물길', '전망대 • 등대 • 전망대 & 타워',
       '역사 및 문화 유산 투어', '동굴 • 지층', '물길 • 폭포', '유서 깊은 산책로 • 공원',
       '인근 지역 • 건축물 • 유령 마을', '교회 & 성당', '유서 깊은 산책로', '자연사 박물관',
       '전망대 • 경관이 좋은 산책로', '전문 박물관 • 즐길거리 & 랜드마크', '물길 • 자연 & 야생동물 서식지',
       '역사적인 장소 • 종교적인 장소', '폭포', '전문 박물관 • 수족관',
       '역사적인 장소 • 인근 지역 • 유서 깊은 산책로', '종교시설',
       '역사적인 장소 • 즐길거리 & 랜드마크 • 동굴', '보트 투어 • 페리', '음식 & 음료 축제',
       '역사적인 장소 • 물길 • 공원', '유서 깊은 산책로 • 경관이 좋은 산책로',
       '자연 & 야생동물 서식지 • 경관이 좋은 산책로', '호텔', '전문 박물관 • 역사박물관',
       '종교적인 장소 • 경관이 좋은 산책로', '성', '농장', '산 • 공원', '아트갤러리 • 아트뮤지엄',
       '모르겠어요.. 데이트 명소라고 알고 있는데 그게 맞나요? 그냥 입구에서 표 안끊고 아.. 이렇구나 하고 왔는데 눈 오면 나름 예쁠것도 같고...... 바로 옆에서 커피 마시고 빠잇',
       '온천 리조트 • 스파', '공원 • 산림', '역사적인 장소 • 가든', '경전철 서비스',
       '아트뮤지엄 • 역사박물관', '해변 & 풀 클럽', '역사적인 장소 • 즐길거리 & 랜드마크 • 교육적인 장소',
       '즐길거리 & 랜드마크 • 부두 & 보드워크 • 등대', '관측소 & 천체투영관', '전차',
       '즐길거리 & 랜드마크 • 전망대 & 타워', '즐길거리 & 랜드마크 • 기념비 및 동상',
       '역사적인 장소 • 종교적인 장소 • 기념비 및 동상', '역사적인 장소 • 유서 깊은 산책로', '철경 철도선로',
       '역사적인 장소 • 성 • 군사 기지 및 시설', '즐길거리 & 랜드마크 • 공원 • 경관이 좋은 산책로',
       '역사적인 장소 • 고대 유적', '역사적인 장소 • 인근 지역 • 즐길거리 & 랜드마크',
       '역사적인 장소 • 인근 지역', '즐길거리 & 랜드마크 • 공원', '전문 박물관 • 아트뮤지엄 • 역사박물관',
       '역사건축물', '온열 스파', '산 • 하이킹 트레일 • 산림', '경관이 좋은 산책로', '역사적인 장소 • 묘지',
       '역사적인 장소 • 기념비 및 동상', '즐길거리 & 랜드마크 • 미스테리한 장소 • 경관이 좋은 산책로',
       '군사 박물관 • 즐길거리 & 랜드마크', '즐길거리 & 랜드마크 • 경관이 좋은 산책로', '고대 유적 • 국립공원',
       '물길 • 계곡', '전망대', '공원 • 경관이 좋은 산책로',
       '즐길거리 & 랜드마크 • 건축물 • 전망대 • 기념비 및 동상', '수족관', '도서관',
       '즐길거리 & 랜드마크 • 브리지', '놀이공원 & 테마파크 • 동굴', '화산', '즐길거리 & 랜드마크 • 지층',
       '군사 박물관 • 역사박물관', '산 • 국립공원 • 산림', '전문 박물관 • 공원 • 커피숍 • 가든',
       '역사적인 장소 • 고대 유적 • 즐길거리 & 랜드마크', '공원 • 교육적인 장소', '산 • 지층',
       '지층 • 경관이 좋은 산책로', '지층', '역사적인 장소 • 군사 기지 및 시설'], dtype=object)

In [10]:
df_a.groupby('분류').count()

                 여행지
분류
가든                 6
가든 • 경관이 좋은 산책로    1
가든 • 아트뮤지엄         1
강연 & 워크숍 • 농장      1
건축물                2
...              ...
하이킹 트레일            2
해변                26
해변 & 풀 클럽          1
호텔                 2
화산                 2

[166 rows x 1 columns]

In [3]:
from sklearn.model_selection import train_test_split

train_x, test_x, train_y, test_y = train_test_split(review, target, test_size=0.2, random_state=0)

NameError: name 'review' is not defined